pingidentity/pf-authn-js-widget

src/index.js

Added a hook for states to register methods that will be called right after that states handlebar template has been rendered.

Add post render callback method to allow states to do custom stuff.

---

src/index.js
src/partials/external_authentication_completed.hbs
src/partials/external_authentication_failed.hbs
src/partials/external_authentication_required.hbs
src/partials/initial_spinner.hbs
src/partials/username_password_required.hbs
src/store.js

Additions to handle `EXTERNAL_AUTHENICATION_REQUIRED`, `EXTERNAL_AUTHENICATION_COMPLETED` and `EXTERNAL_AUTHENICATION_FAILED` and how to handle `POP_UP` and `REDIRECT` in `EXTERNAL_AUTHENICATION_REQUIRED`.

External Authentication

---

src/partials/reference_id_required.hbs

update error icon after authn sources updates to use new UI

agentless error icon

---

README.md

The PingFederate Configuration instructions now reflect the new UI as of PingFederate release 10.1.
#31

Updated the PingFederate Configuration instructions

---

package.json

What: npm audit was reporting security vulnerabilities including a high issue.
How: updating copy-webpack-plugin addresses the high issue with a dependency.

Updating webpack dependencies to address issues reported by npm audit.

---

src/partials/reference_id_required.hbs

enableSubmit() is enabling the submit button - want to have all buttons be disabled for this handlebar.

prevent widget code to enable submit button

---

docs/riskAuthentication.md
src/index.js
src/partials/device_profile_required.hbs

Making changes to support ThreatMetrix adapter

Threatmetrix

---

src/index.js
src/partials/current_credentials_required.hbs
src/partials/new_password_required.hbs

We have added a new model and a new page to only provide current credentials during password change.

Pwd change policy

---

README.md
docs/supportedIntegrations.md
src/index.js
src/partials/id_verification_completed.hbs
src/partials/id_verification_failed.hbs
src/partials/id_verification_in_progress.hbs
src/partials/id_verification_required.hbs
src/partials/id_verification_timed_out.hbs
src/store.js

Edit: SQE completed!
Haven't gone through SQE yet, but creating a pull request for review, thank you!

Pingone verify

---

package.json

Change version for release. Update high vulnerabilities packages

---

docs/supportedIntegrations.md

- Added jamf to the list of supported integrations.

---

package.json

Updated packages with severe security warnings

Updated node engine requirements

---

src/partials/device_profile_session_id_required.hbs

* Add template for DEVICE_PROFILE_SESSION_ID_REQUIRED state

Add support for ThreatMetrix mobile native device profiling state

---

docs/supportedIntegrations.md

Added Microsoft CIC to supportedIntegration.md

Added Microsoft CIC to supportedIntegration.md

---

docs/supportedIntegrations.md
src/index.js
src/partials/authenticator_selection_required.hbs
src/partials/input_required.hbs
src/partials/user_id_required.hbs
src/scss/main.scss

* Add Entrust AuthN API states, associated handlebar files
* Ad handlers for Entrust AuthN states
* Update supported integration page to link to Entrust IK

IK-2935 - Entrust adapter updates

---

demo-server/templates/index-template.handlebars
docs/redirectless.md
src/index.js
src/partials/oauth_device_completed.hbs
src/partials/oauth_device_user_code_confirmation_required.hbs
src/partials/oauth_device_user_code_required.hbs
src/utils/redirectless.js
src/validators/redirectless.js
webpack.config.js

- Added new states, actions and partials
- Added 'user_authz' endpoint interaction when redirectless is in use.
- redirectless documentation update
- fixed redirectless dev server params and minor code cleanups.

OAuth 2.0 Device Authorization user code support

---

types/index.d.ts

This is to import the change from https://github.com/pingidentity/pf-authn-js-widget/pull/113

Fix typescript definitions to use the correct interfaces

---

src/index.js
src/partials/one_time_device_otp_input_required.hbs
src/partials/one_time_device_otp_method_type_input_required.hbs

1) Code changes to support one-time device OTP auth flow
2) Resolved an escaped defect to show/hide back button depending on MFA adapter configuration.

Support one-time device OTP authentication flow

---

package.json

- dev server is not starting in some cases because @babel/plugin-proposal-private-property-in-object is not present, adding thew dev dependency

Added new dev dependency

---

src/partials/input_required.hbs

Added support to handle token push with mutual challenge for Entrust authentication flow (IK-3463)

Added support to handle token push with mutual challenge for Entrust authentication flow

---

src/index.js
src/partials/identifier_required.hbs

Adds risk provider to ID first templates

PF-34415 Add CAPTCHA/reCAPTCHA support on ID First Adapter page

---

src/partials/input_required.hbs

* Add resend functionality for valid Entrust authenticators

IK-3511 - Add resend functionality to javascript widget

---

src/partials/id_verification_failed.hbs

Updating a message in the id_verification_failed.hbs to improve UX
Change 'Cancel' to 'Retry'

Change Cancel to Retry
